apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/rogerdavila/platform-info-api
    newTag: dcff5a3c8fbbc7774a5c9ed68e3ae0e03a62cbab

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: dev
    target:
      kind: Deployment
      name: platform-info-api
