apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/rogerdavila/platform-info-api
    newTag: 3f19c24b5490f8c157846a2f1071ab961733c413

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: dev
    target:
      kind: Deployment
      name: platform-info-api
