apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/rogerdavila/platform-info-api
    newName: k3d-registry.localhost:5050/platform-info-api
    newTag: latest

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: dev
    target:
      kind: Deployment
      name: platform-info-api
